# Development conda environment
# usage: $ mamba env create -f environment.yml
name: somata
channels:
  - conda-forge
dependencies:
  - numpy>=1.23
  - codetiming
  - colorcet
  - ipdb
  - joblib
  - kneed
  - matplotlib
  - pip
  - pytest
  - python
  - scipy
  - setuptools
  - spectrum
  - tqdm
