# Development conda environment
# usage: $ mamba env create -f environment.yml
name: somata
channels:
  - conda-forge
dependencies:
  - ipdb
  - joblib
  - kneed
  - librosa
  - matplotlib
  - numpy>=1.22
  - pip
  - pytest
  - python>=3.8
  - scipy
  - setuptools
  - tqdm
  - pip:
    - spectrum
    - codetiming
    - sorcery>=0.2.2
