# Development conda environment
# usage: $ mamba env create -f environment.yml
name: somata
channels:
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - pytorch
  - cmdstanpy
  - codetiming
  - colorcet
  - ipdb
  - joblib
  - kneed
  - matplotlib
  - mne
  - pip
  - pytest
  - python
  - scipy
  - setuptools
  - tqdm
  - pip:
    - spectrum
